env:
  contexts:
  - name: CSA_Test
    urls:
    - http://localhost:9091/auth/simple-json-cookie/
    includePaths:
    - http://localhost:9091/auth/simple-json-cookie/.*
    authentication:
      method: client
      parameters:
        script: ./dev_csa.zst
        scriptEngine: Mozilla Zest
      verification:
        method: poll
        loggedInRegex: \Q 200 OK\E
        loggedOutRegex: \Q 403 Forbidden\E
        pollFrequency: 60
        pollUnits: seconds
        pollUrl: http://localhost:9091/auth/simple-json-cookie/user
        pollPostData: ""
    sessionManagement:
      method: headers
      parameters:
        Cookie: "sid={%cookie:sid%}; _random=blahblah"
    technology: {}
    structure: {}
    users:
    - name: test
      credentials:
        username: test@test.com
        password: password123
  parameters: {}
jobs:
- type: spiderClient
  parameters:
    context: CSA_Test
    user: test
    maxDuration: 1
    maxChildren: 0
    browserId: firefox-headless
  tests:
  - name: spiderClient/url
    type: url
    onFail: INFO
    url: http://localhost:9091/auth/simple-json-cookie/s3cr3t.html
    operator: and

