env:
  contexts:
  - name: BBA_Test
  urls:
  - http://localhost:9091/auth/simple-json-cookie/
  includePaths:
  - http://localhost:9091/auth/simple-json-cookie/.*
    authentication:
      method: browser
      parameters:
        loginPageUrl: http://localhost:9091/auth/simple-json-cookie/
        loginPageWait: 1
        browserId: firefox-headless
        steps: []
      verification:
        method: poll
        loggedInRegex: \Q 200 OK\E
        loggedOutRegex: \Q 403 Forbidden\E
        pollFrequency: 60
        pollUnits: requests
        pollUrl: http://localhost:9091/auth/simple-json-cookie/user
        pollPostData: ""
    sessionManagement:
      method: headers
      parameters:
        Cookie: "sid={%cookie:sid%}; _random=blahblah"
    technology: {}
    structure: {}
    users:
    - name: test@test.com
      credentials:
        password: password123
        username: test@test.com
  parameters: {}
jobs:
- type: spiderClient
  parameters:
    context: BBA_Test
    user: test@test.com
    maxDuration: 1
    maxChildren: 0
    browserId: firefox-headless
  tests:
  - name: spiderClient/url
    type: url
    onFail: INFO
    url: http://localhost:9091/auth/simple-json-cookie/s3cr3t.html
    operator: and
